# INFO 3401 – Homework 4


In this homework, you will gain practice performing exploratory data analysis of a new data set using SQL. The homework is similar to homework two -- only this time you will again pick the dataset, the question, and your plan for analysis. There is also a question on hypothesis testing and quantitative reasoning. SQL is a very, very common data science tool and it makes sense to spend time practicing SQL to solidify and reinforce your understanding of databases. This homework is intended to give you this opportunity.

In the real world, doing data analysis is not a matter of completing steps assigned to you by an instructor. So in this HW, like in HW3, you will get the chance to investigate your own question. You are highly encouraged to challenge yourself and really investigate something that is interesting to you while doing this assignment.

What SQL do we know? 
1. SELECT 
2. INSERT 
3. We know WHERE clause 
4. We know JOINS
5. We know aggregration (e.g. MAX, MIN, AVG. etc)
6. We know GROUP BY 
7. We know LIMIT
8. We know ORDER BY

## Step 0: Load libraries

Load the libraries you need. You will probably want to load utilities for reading sqlite files, like we used in class in our SQL unit.

In [3]:
import sqlite3
import pandas as pd
import altair as alt
import numpy as np

## Step 1: Pick a dataset

In this step, you should pick a dataset that looks interesting to you. Any relational dataset (i.e. SQLlite database) that looks interesting to you and allows you to do data analysis would be appropriate for this assignment. You might want to try [Kaggle](https://www.kaggle.com/datasets?fileType=sqlite), Google [dataset search](https://datasetsearch.research.google.com/) or Prof. Keegan's [list](https://medium.com/information-expositions/list-of-lists-of-datasets-c9bf52370755) of datasets for ideas. **You must use a sqlite file for this assignment**.

In [5]:
# https://www.kaggle.com/thoughtvector/podcastreviews
con = sqlite3.connect("database.sqlite")

In this cell, briefly explain what questions you are curious to ask, using this dataset.

**What categories of podcasts have the highest  and lowest average review ratings?**

## Step 2: Read in the data

Download the sqlite file and load it in your notebook. Use `SELECT` statements with `LIMIT` clauses to investigate a few tables in the database, like in the in-class examples from our SQL unit. What tables do you see? Explain what you think two of the tables represent.

From code below you can see that there are four tables in this database.

1. Podcast: Contains information about each podcast
2. Reviews: Contains information about the reviews given for the podcasts
3. Categories: Contains information about the podcast categories

In [6]:
db_name = pd.read_sql("PRAGMA database_list;", con)["name"][0]

list_tables = "SELECT * FROM {}.sqlite_master WHERE type='table';".format(db_name)

pd.read_sql(list_tables , con=con)

,type,name,tbl_name,rootpage,sql
0,table,runs,runs,2,CREATE TABLE runs (\n run_at text not n...
1,table,podcasts,podcasts,3,CREATE TABLE podcasts (\n podcast_id te...
2,table,categories,categories,5,CREATE TABLE categories (\n podcast_id ...
3,table,reviews,reviews,7,CREATE TABLE reviews (\n podcast_id tex...

In [15]:
pod_table = '''SELECT * from podcasts'''

reviews_table = '''SELECT * from reviews'''

runs_table = '''SELECT * from runs'''

categories_table = '''SELECT * from categories'''

In [16]:
pd.read_sql_query(pod_table, con)

,podcast_id,itunes_id,slug,itunes_url,title
0,a00018b54eb342567c94dacfb2a3e504,1313466221,scaling-global,https://podcasts.apple.com/us/podcast/scaling-...,Scaling Global
1,a00043d34e734b09246d17dc5d56f63c,158973461,cornerstone-baptist-church-of-orlando,https://podcasts.apple.com/us/podcast/cornerst...,Cornerstone Baptist Church of Orlando
2,a0004b1ef445af9dc84dad1e7821b1e3,139076942,mystery-dancing-in-the-dark,https://podcasts.apple.com/us/podcast/mystery-...,Mystery: Dancing in the Dark
3,a00071f9aaae9ac725c3a586701abf4d,1332508972,kts-money-matters,https://podcasts.apple.com/us/podcast/kts-mone...,KTs Money Matters
4,a000aa69852b276565c4f5eb9cdd999b,1342447811,speedway-soccer,https://podcasts.apple.com/us/podcast/speedway...,Speedway Soccer
...,...,...,...,...,...
46688,fffe3f208a56dfecfaf6d0a7f8399d63,1420703219,how-travel-writers-self-publish,https://podcasts.apple.com/us/podcast/how-trav...,How Travel Writers Self-Publish
46689,fffeb7d6d05f2b4c600fbebc828ca656,1220681898,teddy-the-empress-cooking-the-queens,https://podcasts.apple.com/us/podcast/teddy-th...,TEDDY & THE EMPRESS: Cooking the Queens
46690,ffff5db4b5db2d860c49749e5de8a36d,384521934,frankenstein-or-the-modern-prometheus,https://podcasts.apple.com/us/podcast/frankens...,"Frankenstein, or the Modern Prometheus"
46691,ffff66f98c1adfc8d0d6c41bb8facfd0,1435731839,whos-bringing-wine,https://podcasts.apple.com/us/podcast/whos-bri...,Who’s Bringing Wine?
46692,ffff923482740bc21a0fe184865ec2e2,1271277212,tefl-waffle,https://podcasts.apple.com/us/podcast/tefl-waf...,TEFL Waffle

In [17]:
pd.read_sql_query(reviews_table, con)

,podcast_id,title,content,rating,author_id,created_at
0,c61aa81c9b929a66f0c1db6cbe5d8548,really interesting!,Thanks for providing these insights. Really e...,5,F7E5A318989779D,2018-04-24T12:05:16-07:00
1,c61aa81c9b929a66f0c1db6cbe5d8548,Must listen for anyone interested in the arts!!!,Super excited to see this podcast grow. So man...,5,F6BF5472689BD12,2018-05-09T18:14:32-07:00
2,ad4f2bf69c72b8db75978423c25f379e,nauseatingly left,"I'm a liberal myself, but its pretty obvious a...",1,1AB95B8E6E1309E,2019-06-11T14:53:39-07:00
3,ad4f2bf69c72b8db75978423c25f379e,Diverse stories,I find Tedx talks very inspirational but I oft...,5,11BB760AA5DEBD1,2018-05-31T13:08:09-07:00
4,ad4f2bf69c72b8db75978423c25f379e,👍👍👍👍,"I love this podcast, it is so good.",5,D86032C8E57D15A,2019-06-19T13:56:05-07:00
...,...,...,...,...,...,...
1280332,a23e18c73fd942fab41bcf6b6a1571da,Interesting concepts but…,Interesting concepts and topics but the amount...,2,4C3F6BE3495A23D,2021-10-09T07:10:31-07:00
1280333,ae44a724e94dcec1616d6e695e6198ba,"Good podcast, bad music","Not a huge fan of the theme song, but that’s k...",4,938F0A4490CE344,2021-10-09T16:14:02-07:00
1280334,ae44a724e94dcec1616d6e695e6198ba,Small mistakes ruins the show,I feel like if you cut one episode and made ev...,1,D6CBF74E9B2C7FE,2021-10-09T14:32:49-07:00
1280335,ae44a724e94dcec1616d6e695e6198ba,So happy that you went into season 10!,I was actually bummed thinking it would take a...,5,FED395AE84679C4,2021-10-09T11:40:29-07:00
1280336,ae44a724e94dcec1616d6e695e6198ba,Binge-worthy,"I’d give 5 stars to seasons 1, 3, and 9. Loved...",4,5058E0A92FF400B,2021-10-09T10:36:35-07:00

In [18]:
pd.read_sql_query(runs_table, con)

                run_at  max_rowid  reviews_added
0  2021-05-10 02:53:00    3266481        1215223
1  2021-06-06 21:34:36    3300773          13139
2  2021-07-02 18:04:55    3329699          11561
3  2021-08-01 17:54:42    3360315          11855
4  2021-09-02 18:00:30    3390165          11714
5  2021-10-11 05:18:23    3428923          16845

In [19]:
pd.read_sql_query(categories_table, con)

                             podcast_id              category
0      c61aa81c9b929a66f0c1db6cbe5d8548                  arts
1      c61aa81c9b929a66f0c1db6cbe5d8548  arts-performing-arts
2      c61aa81c9b929a66f0c1db6cbe5d8548                 music
3      ad4f2bf69c72b8db75978423c25f379e                  arts
4      ad4f2bf69c72b8db75978423c25f379e           arts-design
...                                 ...                   ...
70986  deb39a2263a770bbb95696b1181c2df4                  arts
70987  deb39a2263a770bbb95696b1181c2df4             education
70988  c02706c8c8627bcc12bbf82b778e2d60       society-culture
70989  c6599a44e2a0e3bfb0e28099e7c7b2d2               tv-film
70990  ab99c44cb967adaa1e470e7abce08628               tv-film

[70991 rows x 2 columns]

## Step 3: Investigate the data

Think back to how we learned how to form questions from SQL databases by exploring the data. Write code to explore the dataset using the SQL statements you have learned in this class. If you are not sure how to do this, you might want to look back on HW2 for ideas. While investigating the data you must: 

1. Perform 1 JOIN
2. Perform 1 GROUP BY
3. Perform 1 aggregation (MIN/MAX/AVG) etc

In [78]:
SQLjoin = '''SELECT avg(rating), reviews.podcast_id, categories.category FROM reviews INNER JOIN categories on
            categories.podcast_id=reviews.podcast_id GROUP BY category ORDER BY avg(rating) DESC;'''
review_categories = pd.read_sql_query(SQLjoin, con).reset_index()

In [79]:
review_categories

,index,avg(rating),podcast_id,category
0,0,4.886550,da7e26f4fbac05a7cfe042d3b5094e8d,business-careers
1,1,4.840909,e9d3ac399910358815e2383a18879002,hinduism
2,2,4.838036,c0c85a2d1e76d735f930b061680864a0,spirituality
3,3,4.826441,f90b974d49b86b2d4d1769519fb478c0,arts-visual-arts
4,4,4.825437,d316ed51360852656c2a0c4548afdef3,business
5,5,4.813476,aa78d7a47e4407824157f82f1fec4436,society-culture-philosophy
6,6,4.810734,dccf254b60350964226dc8f4601c0dcd,religion-spirituality
7,7,4.799872,d5ff46b87d8945d5804d1cf6158f7d48,christianity
8,8,4.795667,ad4f2bf69c72b8db75978423c25f379e,arts-design
9,9,4.794773,ad4f2bf69c72b8db75978423c25f379e,education
10,10,4.783654,b3cb0ce457a79624fe527b49de1e4bf0,islam
11,11,4.783420,c61aa81c9b929a66f0c1db6cbe5d8548,music
12,12,4.783351,a0bcde1acd49ceb517b6d510696dbcb1,arts-food
13,13,4.759481,e2d1001f9de2cadf03b655217c53fcbd,buddhism
14,14,4.747285,a2389559595b5793317b096ffe7ca6fc,kids-family
15,15,4.743745,ebd3c5a59c3f95d1d0c698bd99280c46,society-culture-places-travel
16,16,4.733189,c61aa81c9b929a66f0c1db6cbe5d8548,arts
17,17,4.723951,f4a8f753bd3959e2a631f2eba3c98172,society-culture-personal-journals
18,18,4.695814,c61aa81c9b929a66f0c1db6cbe5d8548,arts-performing-arts
19,19,4.678009,f6676c2a2cf0c2a61e4f72bd1fd6381b,judaism
20,20,4.674277,a80fa0799e28d70797cb04ec7baa0864,business-investing
21,21,4.634242,f3e34977a7c5ab2ef70335a46fc24dd8,comedy
22,22,4.621429,daba71fbd585d3bb50f3588dfac16d91,arts-fashion-beauty
23,23,4.540532,f2970432aad718a000ebac10e48ae6b0,society-culture
24,24,4.536007,b4e5e62762a9654fe35e2ffe67519929,technology
25,25,4.518082,e377a8742595948fda36a2c133b7ed6c,tv-film

Your answers here

## Step 4: Validate the data against another source

Data does not emerge from nowhere! It is deliberately collected and stored as part of social processes. 

Find some aspect of your data and validate it against another source. You will need to write some code and do some research for this. For instance, when we investigated the baseball database we found that certain players had played in dozens of all star games. We could validate that data by checking Wikipedia (another source) to see if the data seemed to accurately represent baseball history. You are highly encouraged to be creative in doing validation. For instance, if you are looking at data about high school graduation rates you might need to compute the mean graduation rate from your dataset and compare it to official graduation statistics provided by school district leaders in news articles. Do the statistics match? Are they close? What might account for discrepancies? To answer this question, you should write code and describe your research, linking to sources where appropriate.

First I created a new dataframe to see podcast popularity to compare with my ratings dataframe. By doing this, I will be able to see any outlying information. For example, if a podcast category has a very low number of reviews, but is on average rated very high. it is likely not a clear representation of its rating.

In [95]:
pd.read_sql("select *, count(category) from categories group by category ORDER BY count(category) DESC", con)

,podcast_id,category,count(category)
0,f2970432aad718a000ebac10e48ae6b0,society-culture,10073
1,f3e34977a7c5ab2ef70335a46fc24dd8,comedy,8080
2,dccf254b60350964226dc8f4601c0dcd,religion-spirituality,7588
3,d316ed51360852656c2a0c4548afdef3,business,6208
4,c61aa81c9b929a66f0c1db6cbe5d8548,arts,5576
5,ad4f2bf69c72b8db75978423c25f379e,education,5334
6,e377a8742595948fda36a2c133b7ed6c,tv-film,5130
7,d5ff46b87d8945d5804d1cf6158f7d48,christianity,4997
8,c61aa81c9b929a66f0c1db6cbe5d8548,music,4123
9,b4e5e62762a9654fe35e2ffe67519929,technology,2328
10,f4a8f753bd3959e2a631f2eba3c98172,society-culture-personal-journals,1668
11,a2389559595b5793317b096ffe7ca6fc,kids-family,1657
12,da7e26f4fbac05a7cfe042d3b5094e8d,business-careers,1399
13,c0c85a2d1e76d735f930b061680864a0,spirituality,1152
14,c61aa81c9b929a66f0c1db6cbe5d8548,arts-performing-arts,1078
15,ebd3c5a59c3f95d1d0c698bd99280c46,society-culture-places-travel,831
16,aa78d7a47e4407824157f82f1fec4436,society-culture-philosophy,765
17,a80fa0799e28d70797cb04ec7baa0864,business-investing,714
18,f90b974d49b86b2d4d1769519fb478c0,arts-visual-arts,710
19,a0bcde1acd49ceb517b6d510696dbcb1,arts-food,606
20,ad4f2bf69c72b8db75978423c25f379e,arts-design,348
21,daba71fbd585d3bb50f3588dfac16d91,arts-fashion-beauty,248
22,f6676c2a2cf0c2a61e4f72bd1fd6381b,judaism,148
23,b3cb0ce457a79624fe527b49de1e4bf0,islam,120
24,e2d1001f9de2cadf03b655217c53fcbd,buddhism,89
25,e9d3ac399910358815e2383a18879002,hinduism,21

Along with this, I was able to visit the podcast website below to confirm that the categories match and was able to confirm the podcast popularity.
https://www.podchaser.com/categories

## Step 5: Make a plot

In this step, you should make some plot to investigate the data. To do this you will need to (1) organize data in SQL, (2) load the data into a dataframe and (3) make a plot. You may need to perform data cleaning or organization at different points in this process.

For instance, while exploring the resume experiment in-class, we made a histogram to investigate the distribution of years of experience among the two groups in the experiment. What plot would help you understand your dataset? You could consider a scatterplot, a line plot, a histogram, a collection of side-by-side histograms, etc.

As in HW3, any plot that illuminates something interesting about your dataset will be OK -- your focus should be less on getting the plot to appear on screen than on visually representing some interesting phenomenon in the data. 

As in HW3, be sure to consider the aesthetics of your plot. For instance, do the plot axis show all of the relevant data? Can people read the labels on your plot? You might want to search for style guides or best practices for data visualization for things to consider for your particular kind of plot.

,podcast_id,category,count(category)
0,f2970432aad718a000ebac10e48ae6b0,society-culture,10073
1,f3e34977a7c5ab2ef70335a46fc24dd8,comedy,8080
2,dccf254b60350964226dc8f4601c0dcd,religion-spirituality,7588
3,d316ed51360852656c2a0c4548afdef3,business,6208
4,c61aa81c9b929a66f0c1db6cbe5d8548,arts,5576
5,ad4f2bf69c72b8db75978423c25f379e,education,5334
6,e377a8742595948fda36a2c133b7ed6c,tv-film,5130
7,d5ff46b87d8945d5804d1cf6158f7d48,christianity,4997
8,c61aa81c9b929a66f0c1db6cbe5d8548,music,4123
9,b4e5e62762a9654fe35e2ffe67519929,technology,2328
10,f4a8f753bd3959e2a631f2eba3c98172,society-culture-personal-journals,1668
11,a2389559595b5793317b096ffe7ca6fc,kids-family,1657
12,da7e26f4fbac05a7cfe042d3b5094e8d,business-careers,1399
13,c0c85a2d1e76d735f930b061680864a0,spirituality,1152
14,c61aa81c9b929a66f0c1db6cbe5d8548,arts-performing-arts,1078
15,ebd3c5a59c3f95d1d0c698bd99280c46,society-culture-places-travel,831
16,aa78d7a47e4407824157f82f1fec4436,society-culture-philosophy,765
17,a80fa0799e28d70797cb04ec7baa0864,business-investing,714
18,f90b974d49b86b2d4d1769519fb478c0,arts-visual-arts,710
19,a0bcde1acd49ceb517b6d510696dbcb1,arts-food,606
20,ad4f2bf69c72b8db75978423c25f379e,arts-design,348
21,daba71fbd585d3bb50f3588dfac16d91,arts-fashion-beauty,248
22,f6676c2a2cf0c2a61e4f72bd1fd6381b,judaism,148
23,b3cb0ce457a79624fe527b49de1e4bf0,islam,120
24,e2d1001f9de2cadf03b655217c53fcbd,buddhism,89
25,e9d3ac399910358815e2383a18879002,hinduism,21

In [94]:
pod_chart = alt.Chart(review_categories).mark_bar().encode(
    x=alt.Y("avg(rating)", axis=alt.Axis(title='Average Review Score'), scale=alt.Scale(zero=False)),
    y=alt.X('category', axis=alt.Axis(title='Podcast Category'))
    
)
pod_chart

alt.Chart(...)

## Step 6: State questions and conclusions

At this point, you should be able to express conclusions about your data. What questions might your data help answer? What did you learn from the dataset that might answer these questions? Answer with a short paragraph below. Your explanation should link to external resources that validate your conclusions, or reflect them in a new light (e.g. news stories that describe anecdotal versions of what you have found from your analysis).

Based off my visualization, some of the highest categories are business careers, spirituality, and Hinduism. On the other hand, some of the lowest scoring categories were Tv-film, Technology, and society/culture. Some questions I have after seeing this centers around the type of person who would listen to these podcasts. For example, Hinduism and spirituality are closely related, so its very possible that generally the these listeners are more just likely to give good reviews. On the other side tv-film and society/culture are also very closely related. it's possible that the same users giving lower reviews for tv are also leaving the low reviews for society culture.

I also wanted to look at the popularity of the podcasts so I counted all the number of reviews and sorted the count by category. From this I learned that Society-culture is by far the most popular, which is interesting because it has low ratings relative to the other categories. Comedy is another example of this, it is the 3rd most popular by review count but also has a very low average rating. If we look at the three highest rated categories, you can also see that they did not receive as many reviews. 

To me, this likely indicates that categories with more reviews will on average have a lower review rating. This makes sense because angry customers are more likely to leave negative reviews than happy customers are to leave positive reviews. 

Why you can't trust negative reviews - https://www.nytimes.com/2018/06/13/smarter-living/trust-negative-product-reviews.html

## Step 7: Propose an experiment

Imagine that you had a budget of $5000 to perform an experiment to ask a follow up question, related to your conclusions. What experiment would you perform? What outcome variable would you measure? What would the null hypothesis be? What would the alternative hypothesis be? Answer with a brief paragraph.

For further research I would like to investigate the question: Are lower rated review categories affected by the total amount of reviews given. 

Null Hypothesis: On Average, categories that have more total reviews will be rated 5 percent lower than categories with less reviews.

Alternative Hypothesis: The Null hypothesis will be rejected if there is less than a 5 percent difference in review rating by category.